swagger: '2.0'
info:
  version: 0.1.0
  title: Benchmark for API Gateway Demo
paths:
  /frameworks:
    get:
      description: |
        list the available frameworks
      operationId: listFrameworks
      tags:
        - Frameworks
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayofFrameworks
            type: array
            items:
              $ref: '#/definitions/Framework'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: |
        add a framework
      operationId: addFramework

      tags:
        - Frameworks
      responses:
        '200':
          description: Successful response
          schema:
            title: ArrayofFrameworks
            type: array
            items:
              $ref: '#/definitions/Framework'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /frameworks/{frameworkID}:
    get:
      summary: Info for a specific framework
      operationId: showFrameworkbyID
      tags:
        - Frameworks
      parameters:
        - name: frameworkID
          in: path
          required: true
          description: The id of the framework to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Framework'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'


definitions:
  Framework:
    type: object
    properties:
      name:
        type: string
      gpu_support:
        type: boolean
      multiple_gpu_support:
        type: boolean
      multiple_machine_support:
        type: boolean

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
