swagger: '2.0'
info:
  version: 0.1.0
  title: Benchmark for API Gateway Demo
paths:
  /frameworks:
    get:
      description: |
        list the available frameworks
      operationId: listFrameworks
      tags:
        - Frameworks
      responses:
        '200':
          description: listOfFramework
          schema:
            title: ArrayofFrameworks
            type: array
            items:
              $ref: '#/definitions/ItemizedFramework'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    post:
      description: |
        add a framework
      operationId: addFramework
      parameters:
        - name: framework
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Framework'
          required: true
      tags:
        - Frameworks
      responses:
        '200':
          description: Null response
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /frameworks/{frameworkID}:
    get:
      summary: Info for a specific framework
      operationId: showFrameworkbyID
      tags:
        - Frameworks
      parameters:
        - name: frameworkID
          in: path
          required: true
          description: The id of the framework to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/ItemizedFramework'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'


definitions:
  ItemizedFramework:
    type: object
    allOf:
      - $ref: '#/definitions/Framework'
      - required:
          - id
        properties:
          id:
            type: integer
            format: int64
  Framework:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      repo_url:
        type: string
      gpu_support:
        type: boolean
      multiple_gpu_support:
        type: boolean
      multiple_machine_support:
        type: boolean

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
